// Copyright © 2023-2024 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

#include <aotriton/runtime.h>
#include <pybind11/pybind11.h>
namespace py = pybind11;

namespace pyaotriton {
#define EV(name) value(#name, name)
  void def_cudaruntime(py::module_& m) {
    py::enum_<cudaError_t>(m, "cudaError_t", py::module_local())
      .EV(cudaSuccess)
      .EV(cudaErrorInvalidValue)
      // .EV(cudaErrorOutOfMemory)
      .EV(cudaErrorMemoryAllocation)
      // .EV(cudaErrorNotInitialized)
      .EV(cudaErrorInitializationError)
      .EV(cudaErrorDeviceUninitialized)
      .EV(cudaErrorProfilerDisabled)
      .EV(cudaErrorProfilerNotInitialized)
      .EV(cudaErrorProfilerAlreadyStarted)
      .EV(cudaErrorProfilerAlreadyStopped)
      .EV(cudaErrorInvalidConfiguration)
      .EV(cudaErrorInvalidPitchValue)
      .EV(cudaErrorInvalidSymbol)
      .EV(cudaErrorInvalidDevicePointer)
      .EV(cudaErrorInvalidMemcpyDirection)
      .EV(cudaErrorInsufficientDriver)
      .EV(cudaErrorMissingConfiguration)
      .EV(cudaErrorPriorLaunchFailure)
      .EV(cudaErrorInvalidDeviceFunction)
      .EV(cudaErrorNoDevice)
      .EV(cudaErrorInvalidDevice)
      // .EV(cudaErrorInvalidImage)
      .EV(cudaErrorInvalidDevice)
      .EV(cudaErrorNotMapped)
      .EV(cudaErrorMapBufferObjectFailed)
      .EV(cudaErrorMpsRpcFailure)
      .EV(cudaErrorArrayIsMapped)
      .EV(cudaErrorAlreadyMapped)
      .EV(cudaErrorNoKernelImageForDevice)
      .EV(cudaErrorAlreadyAcquired)
      .EV(cudaErrorNotMapped)
      .EV(cudaErrorNotMappedAsArray)
      .EV(cudaErrorNotMappedAsPointer)
      .EV(cudaErrorECCUncorrectable)
      .EV(cudaErrorUnsupportedLimit)
      .EV(cudaErrorDeviceAlreadyInUse)
      .EV(cudaErrorPeerAccessUnsupported)
      .EV(cudaErrorInvalidKernelImage)
      .EV(cudaErrorInvalidGraphicsContext)
      .EV(cudaErrorInvalidSource)
      .EV(cudaErrorFileNotFound)
      .EV(cudaErrorSharedObjectSymbolNotFound)
      .EV(cudaErrorSharedObjectInitFailed)
      .EV(cudaErrorOperatingSystem)
      // .EV(cudaErrorInvalidHandle)
      .EV(cudaErrorInvalidResourceHandle)
      .EV(cudaErrorIllegalState)
      // .EV(cudaErrorNotFound)
      .EV(cudaErrorNotReady)
      .EV(cudaErrorIllegalAddress)
      .EV(cudaErrorLaunchOutOfResources)
      .EV(cudaErrorLaunchTimeout)
      .EV(cudaErrorPeerAccessAlreadyEnabled)
      .EV(cudaErrorPeerAccessNotEnabled)
      .EV(cudaErrorSetOnActiveProcess)
      .EV(cudaErrorContextIsDestroyed)
      .EV(cudaErrorAssert)
      .EV(cudaErrorHostMemoryAlreadyRegistered)
      .EV(cudaErrorHostMemoryNotRegistered)
      .EV(cudaErrorLaunchFailure)
      .EV(cudaErrorCooperativeLaunchTooLarge)
      .EV(cudaErrorNotSupported)
      .EV(cudaErrorStreamCaptureUnsupported)
      .EV(cudaErrorStreamCaptureInvalidated)
      .EV(cudaErrorStreamCaptureMerge)
      .EV(cudaErrorStreamCaptureUnmatched)
      .EV(cudaErrorStreamCaptureUnjoined)
      .EV(cudaErrorStreamCaptureIsolation)
      .EV(cudaErrorStreamCaptureImplicit)
      .EV(cudaErrorCapturedEvent)
      .EV(cudaErrorStreamCaptureWrongThread)
      .EV(cudaErrorGraphExecUpdateFailure)
      .EV(cudaErrorUnknown)
      // .EV(cudaErrorRuntimeMemory)
      // .EV(cudaErrorRuntimeOther)
      // .EV(cudaErrorTbd)
      .export_values();
#undef EV
  }
} // namespace pyaotriton
